import { Link } from 'react-router-dom';
import { useAuth } from '@/context/AuthContext';
import { Plane, Sparkles, MapPin, Calendar, DollarSign, CheckSquare } from 'lucide-react';

export default function HomePage() {
  const { user } = useAuth();

  const features = [
    {
      icon: Sparkles,
      title: 'AI-Powered Itineraries',
      description: 'Get personalized day-by-day travel plans generated by Google Gemini AI.',
    },
    {
      icon: MapPin,
      title: 'Hotel Recommendations',
      description: 'Discover curated hotels that match your budget and preferences.',
    },
    {
      icon: DollarSign,
      title: 'Budget Estimation',
      description: 'Know exactly what to expect with detailed cost breakdowns.',
    },
    {
      icon: Calendar,
      title: 'Flexible Editing',
      description: 'Customize every activity, or let AI regenerate any day you want.',
    },
    {
      icon: CheckSquare,
      title: 'Smart Packing Lists',
      description: 'AI-generated packing lists tailored to your destination and interests.',
    },
    {
      icon: Plane,
      title: 'Save & Manage',
      description: 'All your trips saved securely. Access them anytime, anywhere.',
    },
  ];

  return (
    <div className="animate-fade-in">
      {/* Hero */}
      <section className="relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-primary/5 via-transparent to-accent/5" />
        <div className="relative mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-24 sm:py-32 lg:py-40">
          <div className="text-center max-w-3xl mx-auto">
            <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full border border-primary/20 bg-primary/5 text-sm text-primary mb-8">
              <Sparkles className="h-4 w-4" />
              Powered by Google Gemini AI
            </div>

            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold tracking-tight mb-6">
              Plan Your Dream Trip
              <br />
              <span className="gradient-text">With AI Intelligence</span>
            </h1>

            <p className="text-lg sm:text-xl text-muted-foreground mb-10 max-w-2xl mx-auto">
              Generate personalized travel itineraries, hotel recommendations, budget estimates,
              and packing lists — all powered by artificial intelligence.
            </p>

            <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
              <Link
                to={user ? '/trips/new' : '/register'}
                className="w-full sm:w-auto px-8 py-3.5 rounded-xl bg-primary text-primary-foreground font-semibold hover:bg-primary/90 transition-all hover:shadow-lg hover:shadow-primary/25 text-center"
              >
                {user ? 'Create a Trip' : 'Get Started Free'}
              </Link>
              {!user && (
                <Link
                  to="/login"
                  className="w-full sm:w-auto px-8 py-3.5 rounded-xl border border-border text-foreground font-semibold hover:bg-secondary transition-colors text-center"
                >
                  Sign In
                </Link>
              )}
            </div>
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-20 sm:py-28">
        <div className="text-center mb-16">
          <h2 className="text-3xl sm:text-4xl font-bold mb-4">
            Everything You Need to
            <span className="gradient-text"> Travel Smart</span>
          </h2>
          <p className="text-muted-foreground text-lg max-w-2xl mx-auto">
            Our AI handles the planning so you can focus on the adventure.
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {features.map((feature) => (
            <div
              key={feature.title}
              className="group p-6 rounded-2xl bg-card border border-border hover:border-primary/30 transition-all duration-300 hover:shadow-lg hover:shadow-primary/5"
            >
              <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-primary/10 text-primary mb-4 group-hover:bg-primary/20 transition-colors">
                <feature.icon className="h-6 w-6" />
              </div>
              <h3 className="text-lg font-semibold mb-2">{feature.title}</h3>
              <p className="text-sm text-muted-foreground leading-relaxed">{feature.description}</p>
            </div>
          ))}
        </div>
      </section>

      {/* CTA */}
      <section className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 pb-20 sm:pb-28">
        <div className="relative rounded-3xl overflow-hidden">
          <div className="absolute inset-0 bg-gradient-to-r from-primary/20 to-accent/20" />
          <div className="relative glass rounded-3xl p-10 sm:p-16 text-center">
            <h2 className="text-3xl sm:text-4xl font-bold mb-4">
              Ready to Start Planning?
            </h2>
            <p className="text-muted-foreground text-lg mb-8 max-w-xl mx-auto">
              Create your AI-powered itinerary in minutes. No credit card required.
            </p>
            <Link
              to={user ? '/trips/new' : '/register'}
              className="inline-block px-8 py-3.5 rounded-xl bg-primary text-primary-foreground font-semibold hover:bg-primary/90 transition-all hover:shadow-lg hover:shadow-primary/25"
            >
              {user ? 'Create Your Trip' : 'Sign Up Now'}
            </Link>
          </div>
        </div>
      </section>
    </div>
  );
}
